name: CI (Build & Test)

on:
  push:
    branches: [ "dev", "main" , "feat/*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: ${{ DB_PASSWORD }}
          MYSQL_DATABASE: auction
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -uroot -p${{ DB_PASSWORD }}"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10
      mailhog:
        image: mailhog/mailhog:latest
        ports:
          - 1025:1025   # SMTP
          - 8025:8025   # Web UI (디버깅용, 테스트에는 불필요)

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # 테스트 프로필로 실행. application-test.yml을 로드하게 함.
      - name: Build (tests included)
        env:
          SPRING_PROFILES_ACTIVE: local
          # DB
          SPRING_DATASOURCE_URL: jdbc:mysql://127.0.0.1:3306/auction?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
          SPRING_DATASOURCE_USERNAME: root
          SPRING_DATASOURCE_PASSWORD: ${{ DB_PASSWORD }}
          # MAIL (MailHog)
          SPRING_MAIL_HOST: 127.0.0.1
          SPRING_MAIL_PORT: 1025
          SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: false
          SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: false
          # JWT
          JWT_SECRET: ${{  JWT_SECRET }}
          JWT_EXPIRATION: 86400000
        run: ./gradlew clean build --no-daemon
